### ISSUE TITLE
How to get metadata for the review?

### ISSUE THREAD

**Issue by zooreyweb** [zzxslp/Gest#2]
Metadata was mentioned in the below page but not available via downloads. Can you please help
 https://cseweb.ucsd.edu/~jmcauley/datasets.html#google_restaurants

**Comment by waocats** [comment]
I was wondering this as well. I don't see most of the metadata in the files provided.

**Comment by zzxslp** [comment]
Hi, we don't use the meta data for our SIGIR paper so it is not included in the repo. you can find all the raw meta data here: https://drive.google.com/file/d/1W_tW9c1hRkltBMq_TLUohPaEBvH_s6O0/view?usp=share_link

**Comment by Nana2929** [comment]
Hi, the link seems to be no longer available. Can you please fix the link? Thank you!
